name:        th-printf-str
version:     0.1.0
synopsis:    Indefinite package for th-printf
description: Quasiquoters for printf, producing @String@
author:      Jude Taylor
maintainer:  me@jude.xyz
tested-with: GHC == 8.4.3
category:    Text
github:      pikajude/th-printf

defaults: pikajude/hpack-template@v1

dependencies:
  - base == 4.*

library:
  reexported-modules: Language.Haskell.Printf.String
  dependencies:
    - str-justified
    - th-printf-indef
  verbatim:
    mixins: >
      th-printf-indef (Language.Haskell.Printf as Language.Haskell.Printf.String)
        requires (Str as StrJustified)

internal-libraries:
  str-justified:
    source-dirs: src
    dependencies:
      - str-string
