name: th-printf
version: 0.8
synopsis: Quasiquoters for printf
description: Quasiquoters for string and text printf
author: Jude Taylor
maintainer: me@jude.xyz
tested-with: GHC == 8.6.5, GHC == 8.8.4, GHC == 8.10.7, GHC == 9.0.2, GHC == 9.2.7, GHC == 9.4.5, GHC == 9.6.2
extra-source-files:
  - CHANGELOG.md
category: Text
github: pikajude/th-printf

ghc-options: -Wall

flags:
  werror:
    description: Build with -Werror
    default:     False
    manual:      True

when:
  - condition: flag(werror)
    ghc-options: -Werror

dependencies:
  - base >= 4.12 && < 5

library:
  source-dirs: [src, parser]
  exposed-modules:
    - Language.Haskell.Printf
    - Language.Haskell.Printf.Lib
  dependencies:
    - charset
    - containers
    - microlens-platform
    - mtl
    - parsec
    - semigroups
    - template-haskell
    - th-lift
    - transformers
    - text
    - dlist
    - integer-logarithms

tests:
  format:
    source-dirs: tests/printf
    main: format.hs
    dependencies:
      - HUnit
      - QuickCheck
      - hspec
      - template-haskell
      - th-printf
      - text
    ghc-options: -fno-warn-type-defaults
